# Generated by Django 5.0 on 2023-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='nome')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
            ],
        ),
    ]
